library(httptest)

## start_capturing()
## dewi("Japaner")
## dewi("Japanerin")
## dewi("Asiat")
## dewi("Mannheimer")
## dewi("Kommunikationswissenschaftler")
## dewi("Regierungschef")
## dewi("Tormann")
## dewi("Frau")
## dewi("Qwerty")
## dewi("Muslim")
## dewi("EU-Bürger")
## dewi("Sinto")
## dewi("Buch")
## stop_capturing()
